on: deployment_status
jobs:
  publish:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: convert html to pdf
      run: |
        mkdir out
        docker run \
          --rm \
          -v "$(pwd)/out:/workspace" \
          pink33n/html-to-pdf \
          --url https://fabiolune.github.io/ \
          --pdf fabio_lonegro-resume.pdf \
          --include-background || exit 0
        ls -Al out
    - uses: actions/upload-artifact@v3
      with:
        name: resume
        path: out